# Generated by Django 3.1.5 on 2021-01-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meajudaaajudar', '0004_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causa', models.CharField(max_length=200)),
                ('subCausa', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'causa',
            },
        ),
    ]
