# Generated by Django 3.1.5 on 2021-01-23 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meajudaaajudar', '0009_auto_20210123_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidade', to='meajudaaajudar.estado'),
        ),
    ]
