# Generated by Django 3.1.5 on 2021-01-23 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meajudaaajudar', '0012_auto_20210123_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='estado',
            new_name='xaza',
        ),
    ]
