# Generated by Django 3.1.5 on 2021-01-23 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meajudaaajudar', '0013_auto_20210123_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='xaza',
            new_name='estado',
        ),
    ]
