# Generated by Django 3.1.5 on 2021-01-25 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meajudaaajudar', '0017_remove_causa_subcausa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='nome',
            new_name='numero',
        ),
    ]
