# Generated by Django 3.1.5 on 2021-01-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meajudaaajudar', '0019_auto_20210125_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='descricao',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='doar_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='imagem',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='info_doacao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='nome',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='sobre',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
