# Generated by Django 3.1.5 on 2021-01-25 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meajudaaajudar', '0020_auto_20210125_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instituicao', to='meajudaaajudar.cidade'),
        ),
    ]
